//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IISProjektas
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int Id { get; set; }
        public string text { get; set; }
        public int advertisement_id { get; set; }
        public int user_id { get; set; }
        public Nullable<System.DateTime> date_created { get; set; }
    
        public virtual Advertisement Advertisement { get; set; }
        public virtual User User { get; set; }
    }
}
