//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IISProjektas
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserGroup
    {
        public UserGroup()
        {
            this.User_UserGroup = new HashSet<User_UserGroup>();
        }
    
        public int Id { get; set; }
        public string name { get; set; }
        public string permisions { get; set; }
    
        public virtual ICollection<User_UserGroup> User_UserGroup { get; set; }
    }
}
